spring:
  datasource:
    url: jdbc:mysql://localhost:3306/covidmanagement?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: HChc0827
    driver-class-name: com.mysql.jdbc.Driver
  jdbc:
    template:
      query-timeout: 3
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 5000
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        min-idle: 0


mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*Mapper.xml,classpath:mapper/ext/*.xml
  type-aliases-package: com.covidmanage.pojo

server:
  port: 8181

