package com.covidmanage.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SickUserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sick_user
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sick_user
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sick_user
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sick_user
     *
     * @mbg.generated
     */
    public SickUserExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sick_user
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sick_user
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sick_user
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sick_user
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sick_user
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sick_user
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sick_user
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sick_user
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sick_user
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sick_user
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sick_user
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdentityIdIsNull() {
            addCriterion("identity_id is null");
            return (Criteria) this;
        }

        public Criteria andIdentityIdIsNotNull() {
            addCriterion("identity_id is not null");
            return (Criteria) this;
        }

        public Criteria andIdentityIdEqualTo(String value) {
            addCriterion("identity_id =", value, "identityId");
            return (Criteria) this;
        }

        public Criteria andIdentityIdNotEqualTo(String value) {
            addCriterion("identity_id <>", value, "identityId");
            return (Criteria) this;
        }

        public Criteria andIdentityIdGreaterThan(String value) {
            addCriterion("identity_id >", value, "identityId");
            return (Criteria) this;
        }

        public Criteria andIdentityIdGreaterThanOrEqualTo(String value) {
            addCriterion("identity_id >=", value, "identityId");
            return (Criteria) this;
        }

        public Criteria andIdentityIdLessThan(String value) {
            addCriterion("identity_id <", value, "identityId");
            return (Criteria) this;
        }

        public Criteria andIdentityIdLessThanOrEqualTo(String value) {
            addCriterion("identity_id <=", value, "identityId");
            return (Criteria) this;
        }

        public Criteria andIdentityIdLike(String value) {
            addCriterion("identity_id like", value, "identityId");
            return (Criteria) this;
        }

        public Criteria andIdentityIdNotLike(String value) {
            addCriterion("identity_id not like", value, "identityId");
            return (Criteria) this;
        }

        public Criteria andIdentityIdIn(List<String> values) {
            addCriterion("identity_id in", values, "identityId");
            return (Criteria) this;
        }

        public Criteria andIdentityIdNotIn(List<String> values) {
            addCriterion("identity_id not in", values, "identityId");
            return (Criteria) this;
        }

        public Criteria andIdentityIdBetween(String value1, String value2) {
            addCriterion("identity_id between", value1, value2, "identityId");
            return (Criteria) this;
        }

        public Criteria andIdentityIdNotBetween(String value1, String value2) {
            addCriterion("identity_id not between", value1, value2, "identityId");
            return (Criteria) this;
        }

        public Criteria andSickReasonIsNull() {
            addCriterion("sick_reason is null");
            return (Criteria) this;
        }

        public Criteria andSickReasonIsNotNull() {
            addCriterion("sick_reason is not null");
            return (Criteria) this;
        }

        public Criteria andSickReasonEqualTo(String value) {
            addCriterion("sick_reason =", value, "sickReason");
            return (Criteria) this;
        }

        public Criteria andSickReasonNotEqualTo(String value) {
            addCriterion("sick_reason <>", value, "sickReason");
            return (Criteria) this;
        }

        public Criteria andSickReasonGreaterThan(String value) {
            addCriterion("sick_reason >", value, "sickReason");
            return (Criteria) this;
        }

        public Criteria andSickReasonGreaterThanOrEqualTo(String value) {
            addCriterion("sick_reason >=", value, "sickReason");
            return (Criteria) this;
        }

        public Criteria andSickReasonLessThan(String value) {
            addCriterion("sick_reason <", value, "sickReason");
            return (Criteria) this;
        }

        public Criteria andSickReasonLessThanOrEqualTo(String value) {
            addCriterion("sick_reason <=", value, "sickReason");
            return (Criteria) this;
        }

        public Criteria andSickReasonLike(String value) {
            addCriterion("sick_reason like", value, "sickReason");
            return (Criteria) this;
        }

        public Criteria andSickReasonNotLike(String value) {
            addCriterion("sick_reason not like", value, "sickReason");
            return (Criteria) this;
        }

        public Criteria andSickReasonIn(List<String> values) {
            addCriterion("sick_reason in", values, "sickReason");
            return (Criteria) this;
        }

        public Criteria andSickReasonNotIn(List<String> values) {
            addCriterion("sick_reason not in", values, "sickReason");
            return (Criteria) this;
        }

        public Criteria andSickReasonBetween(String value1, String value2) {
            addCriterion("sick_reason between", value1, value2, "sickReason");
            return (Criteria) this;
        }

        public Criteria andSickReasonNotBetween(String value1, String value2) {
            addCriterion("sick_reason not between", value1, value2, "sickReason");
            return (Criteria) this;
        }

        public Criteria andWhenSickIsNull() {
            addCriterion("when_sick is null");
            return (Criteria) this;
        }

        public Criteria andWhenSickIsNotNull() {
            addCriterion("when_sick is not null");
            return (Criteria) this;
        }

        public Criteria andWhenSickEqualTo(String value) {
            addCriterion("when_sick =", value, "whenSick");
            return (Criteria) this;
        }

        public Criteria andWhenSickNotEqualTo(String value) {
            addCriterion("when_sick <>", value, "whenSick");
            return (Criteria) this;
        }

        public Criteria andWhenSickGreaterThan(String value) {
            addCriterion("when_sick >", value, "whenSick");
            return (Criteria) this;
        }

        public Criteria andWhenSickGreaterThanOrEqualTo(String value) {
            addCriterion("when_sick >=", value, "whenSick");
            return (Criteria) this;
        }

        public Criteria andWhenSickLessThan(String value) {
            addCriterion("when_sick <", value, "whenSick");
            return (Criteria) this;
        }

        public Criteria andWhenSickLessThanOrEqualTo(String value) {
            addCriterion("when_sick <=", value, "whenSick");
            return (Criteria) this;
        }

        public Criteria andWhenSickLike(String value) {
            addCriterion("when_sick like", value, "whenSick");
            return (Criteria) this;
        }

        public Criteria andWhenSickNotLike(String value) {
            addCriterion("when_sick not like", value, "whenSick");
            return (Criteria) this;
        }

        public Criteria andWhenSickIn(List<String> values) {
            addCriterion("when_sick in", values, "whenSick");
            return (Criteria) this;
        }

        public Criteria andWhenSickNotIn(List<String> values) {
            addCriterion("when_sick not in", values, "whenSick");
            return (Criteria) this;
        }

        public Criteria andWhenSickBetween(String value1, String value2) {
            addCriterion("when_sick between", value1, value2, "whenSick");
            return (Criteria) this;
        }

        public Criteria andWhenSickNotBetween(String value1, String value2) {
            addCriterion("when_sick not between", value1, value2, "whenSick");
            return (Criteria) this;
        }

        public Criteria andIfFavourIsNull() {
            addCriterion("if_favour is null");
            return (Criteria) this;
        }

        public Criteria andIfFavourIsNotNull() {
            addCriterion("if_favour is not null");
            return (Criteria) this;
        }

        public Criteria andIfFavourEqualTo(String value) {
            addCriterion("if_favour =", value, "ifFavour");
            return (Criteria) this;
        }

        public Criteria andIfFavourNotEqualTo(String value) {
            addCriterion("if_favour <>", value, "ifFavour");
            return (Criteria) this;
        }

        public Criteria andIfFavourGreaterThan(String value) {
            addCriterion("if_favour >", value, "ifFavour");
            return (Criteria) this;
        }

        public Criteria andIfFavourGreaterThanOrEqualTo(String value) {
            addCriterion("if_favour >=", value, "ifFavour");
            return (Criteria) this;
        }

        public Criteria andIfFavourLessThan(String value) {
            addCriterion("if_favour <", value, "ifFavour");
            return (Criteria) this;
        }

        public Criteria andIfFavourLessThanOrEqualTo(String value) {
            addCriterion("if_favour <=", value, "ifFavour");
            return (Criteria) this;
        }

        public Criteria andIfFavourLike(String value) {
            addCriterion("if_favour like", value, "ifFavour");
            return (Criteria) this;
        }

        public Criteria andIfFavourNotLike(String value) {
            addCriterion("if_favour not like", value, "ifFavour");
            return (Criteria) this;
        }

        public Criteria andIfFavourIn(List<String> values) {
            addCriterion("if_favour in", values, "ifFavour");
            return (Criteria) this;
        }

        public Criteria andIfFavourNotIn(List<String> values) {
            addCriterion("if_favour not in", values, "ifFavour");
            return (Criteria) this;
        }

        public Criteria andIfFavourBetween(String value1, String value2) {
            addCriterion("if_favour between", value1, value2, "ifFavour");
            return (Criteria) this;
        }

        public Criteria andIfFavourNotBetween(String value1, String value2) {
            addCriterion("if_favour not between", value1, value2, "ifFavour");
            return (Criteria) this;
        }

        public Criteria andBodyTemperatureIsNull() {
            addCriterion("body_temperature is null");
            return (Criteria) this;
        }

        public Criteria andBodyTemperatureIsNotNull() {
            addCriterion("body_temperature is not null");
            return (Criteria) this;
        }

        public Criteria andBodyTemperatureEqualTo(Double value) {
            addCriterion("body_temperature =", value, "bodyTemperature");
            return (Criteria) this;
        }

        public Criteria andBodyTemperatureNotEqualTo(Double value) {
            addCriterion("body_temperature <>", value, "bodyTemperature");
            return (Criteria) this;
        }

        public Criteria andBodyTemperatureGreaterThan(Double value) {
            addCriterion("body_temperature >", value, "bodyTemperature");
            return (Criteria) this;
        }

        public Criteria andBodyTemperatureGreaterThanOrEqualTo(Double value) {
            addCriterion("body_temperature >=", value, "bodyTemperature");
            return (Criteria) this;
        }

        public Criteria andBodyTemperatureLessThan(Double value) {
            addCriterion("body_temperature <", value, "bodyTemperature");
            return (Criteria) this;
        }

        public Criteria andBodyTemperatureLessThanOrEqualTo(Double value) {
            addCriterion("body_temperature <=", value, "bodyTemperature");
            return (Criteria) this;
        }

        public Criteria andBodyTemperatureIn(List<Double> values) {
            addCriterion("body_temperature in", values, "bodyTemperature");
            return (Criteria) this;
        }

        public Criteria andBodyTemperatureNotIn(List<Double> values) {
            addCriterion("body_temperature not in", values, "bodyTemperature");
            return (Criteria) this;
        }

        public Criteria andBodyTemperatureBetween(Double value1, Double value2) {
            addCriterion("body_temperature between", value1, value2, "bodyTemperature");
            return (Criteria) this;
        }

        public Criteria andBodyTemperatureNotBetween(Double value1, Double value2) {
            addCriterion("body_temperature not between", value1, value2, "bodyTemperature");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCovidTestIsNull() {
            addCriterion("covid_test is null");
            return (Criteria) this;
        }

        public Criteria andCovidTestIsNotNull() {
            addCriterion("covid_test is not null");
            return (Criteria) this;
        }

        public Criteria andCovidTestEqualTo(String value) {
            addCriterion("covid_test =", value, "covidTest");
            return (Criteria) this;
        }

        public Criteria andCovidTestNotEqualTo(String value) {
            addCriterion("covid_test <>", value, "covidTest");
            return (Criteria) this;
        }

        public Criteria andCovidTestGreaterThan(String value) {
            addCriterion("covid_test >", value, "covidTest");
            return (Criteria) this;
        }

        public Criteria andCovidTestGreaterThanOrEqualTo(String value) {
            addCriterion("covid_test >=", value, "covidTest");
            return (Criteria) this;
        }

        public Criteria andCovidTestLessThan(String value) {
            addCriterion("covid_test <", value, "covidTest");
            return (Criteria) this;
        }

        public Criteria andCovidTestLessThanOrEqualTo(String value) {
            addCriterion("covid_test <=", value, "covidTest");
            return (Criteria) this;
        }

        public Criteria andCovidTestLike(String value) {
            addCriterion("covid_test like", value, "covidTest");
            return (Criteria) this;
        }

        public Criteria andCovidTestNotLike(String value) {
            addCriterion("covid_test not like", value, "covidTest");
            return (Criteria) this;
        }

        public Criteria andCovidTestIn(List<String> values) {
            addCriterion("covid_test in", values, "covidTest");
            return (Criteria) this;
        }

        public Criteria andCovidTestNotIn(List<String> values) {
            addCriterion("covid_test not in", values, "covidTest");
            return (Criteria) this;
        }

        public Criteria andCovidTestBetween(String value1, String value2) {
            addCriterion("covid_test between", value1, value2, "covidTest");
            return (Criteria) this;
        }

        public Criteria andCovidTestNotBetween(String value1, String value2) {
            addCriterion("covid_test not between", value1, value2, "covidTest");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sick_user
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sick_user
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}