package com.covidmanage.pojo;

import lombok.Builder;

import java.io.Serializable;
import java.util.Date;

@Builder
public class SupplyNeed implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supply_need.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supply_need.identity_id
     *
     * @mbg.generated
     */
    private String identityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supply_need.supply_type
     *
     * @mbg.generated
     */
    private String supplyType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supply_need.supply_content
     *
     * @mbg.generated
     */
    private String supplyContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supply_need.age
     *
     * @mbg.generated
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supply_need.is_emergency
     *
     * @mbg.generated
     */
    private Integer isEmergency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supply_need.suggestion
     *
     * @mbg.generated
     */
    private String suggestion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supply_need.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supply_need.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table supply_need
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supply_need.id
     *
     * @return the value of supply_need.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supply_need.id
     *
     * @param id the value for supply_need.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supply_need.identity_id
     *
     * @return the value of supply_need.identity_id
     *
     * @mbg.generated
     */
    public String getIdentityId() {
        return identityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supply_need.identity_id
     *
     * @param identityId the value for supply_need.identity_id
     *
     * @mbg.generated
     */
    public void setIdentityId(String identityId) {
        this.identityId = identityId == null ? null : identityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supply_need.supply_type
     *
     * @return the value of supply_need.supply_type
     *
     * @mbg.generated
     */
    public String getSupplyType() {
        return supplyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supply_need.supply_type
     *
     * @param supplyType the value for supply_need.supply_type
     *
     * @mbg.generated
     */
    public void setSupplyType(String supplyType) {
        this.supplyType = supplyType == null ? null : supplyType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supply_need.supply_content
     *
     * @return the value of supply_need.supply_content
     *
     * @mbg.generated
     */
    public String getSupplyContent() {
        return supplyContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supply_need.supply_content
     *
     * @param supplyContent the value for supply_need.supply_content
     *
     * @mbg.generated
     */
    public void setSupplyContent(String supplyContent) {
        this.supplyContent = supplyContent == null ? null : supplyContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supply_need.age
     *
     * @return the value of supply_need.age
     *
     * @mbg.generated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supply_need.age
     *
     * @param age the value for supply_need.age
     *
     * @mbg.generated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supply_need.is_emergency
     *
     * @return the value of supply_need.is_emergency
     *
     * @mbg.generated
     */
    public Integer getIsEmergency() {
        return isEmergency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supply_need.is_emergency
     *
     * @param isEmergency the value for supply_need.is_emergency
     *
     * @mbg.generated
     */
    public void setIsEmergency(Integer isEmergency) {
        this.isEmergency = isEmergency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supply_need.suggestion
     *
     * @return the value of supply_need.suggestion
     *
     * @mbg.generated
     */
    public String getSuggestion() {
        return suggestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supply_need.suggestion
     *
     * @param suggestion the value for supply_need.suggestion
     *
     * @mbg.generated
     */
    public void setSuggestion(String suggestion) {
        this.suggestion = suggestion == null ? null : suggestion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supply_need.update_time
     *
     * @return the value of supply_need.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supply_need.update_time
     *
     * @param updateTime the value for supply_need.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supply_need.create_time
     *
     * @return the value of supply_need.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supply_need.create_time
     *
     * @param createTime the value for supply_need.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supply_need
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", identityId=").append(identityId);
        sb.append(", supplyType=").append(supplyType);
        sb.append(", supplyContent=").append(supplyContent);
        sb.append(", age=").append(age);
        sb.append(", isEmergency=").append(isEmergency);
        sb.append(", suggestion=").append(suggestion);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}