package com.covidmanage.pojo;

import java.io.Serializable;
import java.util.Date;

public class SupplyInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supply_info.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supply_info.supply_kind
     *
     * @mbg.generated
     */
    private String supplyKind;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supply_info.supply_content
     *
     * @mbg.generated
     */
    private String supplyContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supply_info.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supply_info.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table supply_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supply_info.id
     *
     * @return the value of supply_info.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supply_info.id
     *
     * @param id the value for supply_info.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supply_info.supply_kind
     *
     * @return the value of supply_info.supply_kind
     *
     * @mbg.generated
     */
    public String getSupplyKind() {
        return supplyKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supply_info.supply_kind
     *
     * @param supplyKind the value for supply_info.supply_kind
     *
     * @mbg.generated
     */
    public void setSupplyKind(String supplyKind) {
        this.supplyKind = supplyKind == null ? null : supplyKind.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supply_info.supply_content
     *
     * @return the value of supply_info.supply_content
     *
     * @mbg.generated
     */
    public String getSupplyContent() {
        return supplyContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supply_info.supply_content
     *
     * @param supplyContent the value for supply_info.supply_content
     *
     * @mbg.generated
     */
    public void setSupplyContent(String supplyContent) {
        this.supplyContent = supplyContent == null ? null : supplyContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supply_info.update_time
     *
     * @return the value of supply_info.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supply_info.update_time
     *
     * @param updateTime the value for supply_info.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supply_info.create_time
     *
     * @return the value of supply_info.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supply_info.create_time
     *
     * @param createTime the value for supply_info.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supply_info
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", supplyKind=").append(supplyKind);
        sb.append(", supplyContent=").append(supplyContent);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}