package com.covidmanage.pojo;

import lombok.Builder;

import java.io.Serializable;

@Builder
public class TodoList implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_list.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_list.identity_id
     *
     * @mbg.generated
     */
    private String identityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_list.todo_thing
     *
     * @mbg.generated
     */
    private String todoThing;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_list.is_deleted
     *
     * @mbg.generated
     */
    private Integer isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table todo_list
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_list.id
     *
     * @return the value of todo_list.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_list.id
     *
     * @param id the value for todo_list.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_list.identity_id
     *
     * @return the value of todo_list.identity_id
     *
     * @mbg.generated
     */
    public String getIdentityId() {
        return identityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_list.identity_id
     *
     * @param identityId the value for todo_list.identity_id
     *
     * @mbg.generated
     */
    public void setIdentityId(String identityId) {
        this.identityId = identityId == null ? null : identityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_list.todo_thing
     *
     * @return the value of todo_list.todo_thing
     *
     * @mbg.generated
     */
    public String getTodoThing() {
        return todoThing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_list.todo_thing
     *
     * @param todoThing the value for todo_list.todo_thing
     *
     * @mbg.generated
     */
    public void setTodoThing(String todoThing) {
        this.todoThing = todoThing == null ? null : todoThing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_list.is_deleted
     *
     * @return the value of todo_list.is_deleted
     *
     * @mbg.generated
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_list.is_deleted
     *
     * @param isDeleted the value for todo_list.is_deleted
     *
     * @mbg.generated
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo_list
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", identityId=").append(identityId);
        sb.append(", todoThing=").append(todoThing);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}