package com.covidmanage.pojo;

import java.io.Serializable;

public class TravelInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_info.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_info.picUrl
     *
     * @mbg.generated
     */
    private String picurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_info.province
     *
     * @mbg.generated
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_info.travel_score
     *
     * @mbg.generated
     */
    private Integer travelScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_info.a5_num
     *
     * @mbg.generated
     */
    private Integer a5Num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_info.info
     *
     * @mbg.generated
     */
    private String info;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table travel_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_info.id
     *
     * @return the value of travel_info.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_info.id
     *
     * @param id the value for travel_info.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_info.picUrl
     *
     * @return the value of travel_info.picUrl
     *
     * @mbg.generated
     */
    public String getPicurl() {
        return picurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_info.picUrl
     *
     * @param picurl the value for travel_info.picUrl
     *
     * @mbg.generated
     */
    public void setPicurl(String picurl) {
        this.picurl = picurl == null ? null : picurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_info.province
     *
     * @return the value of travel_info.province
     *
     * @mbg.generated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_info.province
     *
     * @param province the value for travel_info.province
     *
     * @mbg.generated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_info.travel_score
     *
     * @return the value of travel_info.travel_score
     *
     * @mbg.generated
     */
    public Integer getTravelScore() {
        return travelScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_info.travel_score
     *
     * @param travelScore the value for travel_info.travel_score
     *
     * @mbg.generated
     */
    public void setTravelScore(Integer travelScore) {
        this.travelScore = travelScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_info.a5_num
     *
     * @return the value of travel_info.a5_num
     *
     * @mbg.generated
     */
    public Integer getA5Num() {
        return a5Num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_info.a5_num
     *
     * @param a5Num the value for travel_info.a5_num
     *
     * @mbg.generated
     */
    public void setA5Num(Integer a5Num) {
        this.a5Num = a5Num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_info.info
     *
     * @return the value of travel_info.info
     *
     * @mbg.generated
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_info.info
     *
     * @param info the value for travel_info.info
     *
     * @mbg.generated
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_info
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", picurl=").append(picurl);
        sb.append(", province=").append(province);
        sb.append(", travelScore=").append(travelScore);
        sb.append(", a5Num=").append(a5Num);
        sb.append(", info=").append(info);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}