package com.covidmanage.pojo;

import lombok.Builder;

import java.io.Serializable;
import java.util.Date;

@Builder
public class VaccineReservation implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vaccine_reservation.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vaccine_reservation.identity_id
     *
     * @mbg.generated
     */
    private String identityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vaccine_reservation.real_name
     *
     * @mbg.generated
     */
    private String realName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vaccine_reservation.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vaccine_reservation.hospital_name
     *
     * @mbg.generated
     */
    private String hospitalName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vaccine_reservation.vaccine_status
     *
     * @mbg.generated
     */
    private Integer vaccineStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vaccine_reservation.vaccine_type
     *
     * @mbg.generated
     */
    private Integer vaccineType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vaccine_reservation.picUrl
     *
     * @mbg.generated
     */
    private String picurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vaccine_reservation.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vaccine_reservation.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vaccine_reservation
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vaccine_reservation.id
     *
     * @return the value of vaccine_reservation.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vaccine_reservation.id
     *
     * @param id the value for vaccine_reservation.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vaccine_reservation.identity_id
     *
     * @return the value of vaccine_reservation.identity_id
     *
     * @mbg.generated
     */
    public String getIdentityId() {
        return identityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vaccine_reservation.identity_id
     *
     * @param identityId the value for vaccine_reservation.identity_id
     *
     * @mbg.generated
     */
    public void setIdentityId(String identityId) {
        this.identityId = identityId == null ? null : identityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vaccine_reservation.real_name
     *
     * @return the value of vaccine_reservation.real_name
     *
     * @mbg.generated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vaccine_reservation.real_name
     *
     * @param realName the value for vaccine_reservation.real_name
     *
     * @mbg.generated
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vaccine_reservation.phone
     *
     * @return the value of vaccine_reservation.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vaccine_reservation.phone
     *
     * @param phone the value for vaccine_reservation.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vaccine_reservation.hospital_name
     *
     * @return the value of vaccine_reservation.hospital_name
     *
     * @mbg.generated
     */
    public String getHospitalName() {
        return hospitalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vaccine_reservation.hospital_name
     *
     * @param hospitalName the value for vaccine_reservation.hospital_name
     *
     * @mbg.generated
     */
    public void setHospitalName(String hospitalName) {
        this.hospitalName = hospitalName == null ? null : hospitalName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vaccine_reservation.vaccine_status
     *
     * @return the value of vaccine_reservation.vaccine_status
     *
     * @mbg.generated
     */
    public Integer getVaccineStatus() {
        return vaccineStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vaccine_reservation.vaccine_status
     *
     * @param vaccineStatus the value for vaccine_reservation.vaccine_status
     *
     * @mbg.generated
     */
    public void setVaccineStatus(Integer vaccineStatus) {
        this.vaccineStatus = vaccineStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vaccine_reservation.vaccine_type
     *
     * @return the value of vaccine_reservation.vaccine_type
     *
     * @mbg.generated
     */
    public Integer getVaccineType() {
        return vaccineType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vaccine_reservation.vaccine_type
     *
     * @param vaccineType the value for vaccine_reservation.vaccine_type
     *
     * @mbg.generated
     */
    public void setVaccineType(Integer vaccineType) {
        this.vaccineType = vaccineType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vaccine_reservation.picUrl
     *
     * @return the value of vaccine_reservation.picUrl
     *
     * @mbg.generated
     */
    public String getPicurl() {
        return picurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vaccine_reservation.picUrl
     *
     * @param picurl the value for vaccine_reservation.picUrl
     *
     * @mbg.generated
     */
    public void setPicurl(String picurl) {
        this.picurl = picurl == null ? null : picurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vaccine_reservation.update_time
     *
     * @return the value of vaccine_reservation.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vaccine_reservation.update_time
     *
     * @param updateTime the value for vaccine_reservation.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vaccine_reservation.create_time
     *
     * @return the value of vaccine_reservation.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vaccine_reservation.create_time
     *
     * @param createTime the value for vaccine_reservation.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vaccine_reservation
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", identityId=").append(identityId);
        sb.append(", realName=").append(realName);
        sb.append(", phone=").append(phone);
        sb.append(", hospitalName=").append(hospitalName);
        sb.append(", vaccineStatus=").append(vaccineStatus);
        sb.append(", vaccineType=").append(vaccineType);
        sb.append(", picurl=").append(picurl);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}