package com.covidmanage.pojo;

import java.io.Serializable;
import java.util.Date;

public class VaccineLocation implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vaccine_location.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vaccine_location.hospital_name
     *
     * @mbg.generated
     */
    private String hospitalName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vaccine_location.hospital_location
     *
     * @mbg.generated
     */
    private String hospitalLocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vaccine_location.hostipal_tel
     *
     * @mbg.generated
     */
    private String hostipalTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vaccine_location.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vaccine_location.picUrl
     *
     * @mbg.generated
     */
    private String picurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vaccine_location.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vaccine_location.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vaccine_location
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vaccine_location.id
     *
     * @return the value of vaccine_location.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vaccine_location.id
     *
     * @param id the value for vaccine_location.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vaccine_location.hospital_name
     *
     * @return the value of vaccine_location.hospital_name
     *
     * @mbg.generated
     */
    public String getHospitalName() {
        return hospitalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vaccine_location.hospital_name
     *
     * @param hospitalName the value for vaccine_location.hospital_name
     *
     * @mbg.generated
     */
    public void setHospitalName(String hospitalName) {
        this.hospitalName = hospitalName == null ? null : hospitalName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vaccine_location.hospital_location
     *
     * @return the value of vaccine_location.hospital_location
     *
     * @mbg.generated
     */
    public String getHospitalLocation() {
        return hospitalLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vaccine_location.hospital_location
     *
     * @param hospitalLocation the value for vaccine_location.hospital_location
     *
     * @mbg.generated
     */
    public void setHospitalLocation(String hospitalLocation) {
        this.hospitalLocation = hospitalLocation == null ? null : hospitalLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vaccine_location.hostipal_tel
     *
     * @return the value of vaccine_location.hostipal_tel
     *
     * @mbg.generated
     */
    public String getHostipalTel() {
        return hostipalTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vaccine_location.hostipal_tel
     *
     * @param hostipalTel the value for vaccine_location.hostipal_tel
     *
     * @mbg.generated
     */
    public void setHostipalTel(String hostipalTel) {
        this.hostipalTel = hostipalTel == null ? null : hostipalTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vaccine_location.type
     *
     * @return the value of vaccine_location.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vaccine_location.type
     *
     * @param type the value for vaccine_location.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vaccine_location.picUrl
     *
     * @return the value of vaccine_location.picUrl
     *
     * @mbg.generated
     */
    public String getPicurl() {
        return picurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vaccine_location.picUrl
     *
     * @param picurl the value for vaccine_location.picUrl
     *
     * @mbg.generated
     */
    public void setPicurl(String picurl) {
        this.picurl = picurl == null ? null : picurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vaccine_location.update_time
     *
     * @return the value of vaccine_location.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vaccine_location.update_time
     *
     * @param updateTime the value for vaccine_location.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vaccine_location.create_time
     *
     * @return the value of vaccine_location.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vaccine_location.create_time
     *
     * @param createTime the value for vaccine_location.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vaccine_location
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", hospitalName=").append(hospitalName);
        sb.append(", hospitalLocation=").append(hospitalLocation);
        sb.append(", hostipalTel=").append(hostipalTel);
        sb.append(", type=").append(type);
        sb.append(", picurl=").append(picurl);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}