package com.covidmanage.pojo;

import java.io.Serializable;
import java.util.Date;

public class VerifyUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verify_user.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verify_user.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verify_user.identity_id
     *
     * @mbg.generated
     */
    private String identityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verify_user.sex
     *
     * @mbg.generated
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verify_user.nationality
     *
     * @mbg.generated
     */
    private String nationality;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verify_user.birth
     *
     * @mbg.generated
     */
    private String birth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verify_user.start_date
     *
     * @mbg.generated
     */
    private String startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verify_user.end_date
     *
     * @mbg.generated
     */
    private String endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verify_user.issue
     *
     * @mbg.generated
     */
    private String issue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verify_user.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verify_user.face_url
     *
     * @mbg.generated
     */
    private String faceUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verify_user.back_url
     *
     * @mbg.generated
     */
    private String backUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verify_user.sign_url
     *
     * @mbg.generated
     */
    private String signUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verify_user.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verify_user.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table verify_user
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verify_user.id
     *
     * @return the value of verify_user.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verify_user.id
     *
     * @param id the value for verify_user.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verify_user.name
     *
     * @return the value of verify_user.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verify_user.name
     *
     * @param name the value for verify_user.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verify_user.identity_id
     *
     * @return the value of verify_user.identity_id
     *
     * @mbg.generated
     */
    public String getIdentityId() {
        return identityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verify_user.identity_id
     *
     * @param identityId the value for verify_user.identity_id
     *
     * @mbg.generated
     */
    public void setIdentityId(String identityId) {
        this.identityId = identityId == null ? null : identityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verify_user.sex
     *
     * @return the value of verify_user.sex
     *
     * @mbg.generated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verify_user.sex
     *
     * @param sex the value for verify_user.sex
     *
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verify_user.nationality
     *
     * @return the value of verify_user.nationality
     *
     * @mbg.generated
     */
    public String getNationality() {
        return nationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verify_user.nationality
     *
     * @param nationality the value for verify_user.nationality
     *
     * @mbg.generated
     */
    public void setNationality(String nationality) {
        this.nationality = nationality == null ? null : nationality.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verify_user.birth
     *
     * @return the value of verify_user.birth
     *
     * @mbg.generated
     */
    public String getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verify_user.birth
     *
     * @param birth the value for verify_user.birth
     *
     * @mbg.generated
     */
    public void setBirth(String birth) {
        this.birth = birth == null ? null : birth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verify_user.start_date
     *
     * @return the value of verify_user.start_date
     *
     * @mbg.generated
     */
    public String getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verify_user.start_date
     *
     * @param startDate the value for verify_user.start_date
     *
     * @mbg.generated
     */
    public void setStartDate(String startDate) {
        this.startDate = startDate == null ? null : startDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verify_user.end_date
     *
     * @return the value of verify_user.end_date
     *
     * @mbg.generated
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verify_user.end_date
     *
     * @param endDate the value for verify_user.end_date
     *
     * @mbg.generated
     */
    public void setEndDate(String endDate) {
        this.endDate = endDate == null ? null : endDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verify_user.issue
     *
     * @return the value of verify_user.issue
     *
     * @mbg.generated
     */
    public String getIssue() {
        return issue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verify_user.issue
     *
     * @param issue the value for verify_user.issue
     *
     * @mbg.generated
     */
    public void setIssue(String issue) {
        this.issue = issue == null ? null : issue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verify_user.address
     *
     * @return the value of verify_user.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verify_user.address
     *
     * @param address the value for verify_user.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verify_user.face_url
     *
     * @return the value of verify_user.face_url
     *
     * @mbg.generated
     */
    public String getFaceUrl() {
        return faceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verify_user.face_url
     *
     * @param faceUrl the value for verify_user.face_url
     *
     * @mbg.generated
     */
    public void setFaceUrl(String faceUrl) {
        this.faceUrl = faceUrl == null ? null : faceUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verify_user.back_url
     *
     * @return the value of verify_user.back_url
     *
     * @mbg.generated
     */
    public String getBackUrl() {
        return backUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verify_user.back_url
     *
     * @param backUrl the value for verify_user.back_url
     *
     * @mbg.generated
     */
    public void setBackUrl(String backUrl) {
        this.backUrl = backUrl == null ? null : backUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verify_user.sign_url
     *
     * @return the value of verify_user.sign_url
     *
     * @mbg.generated
     */
    public String getSignUrl() {
        return signUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verify_user.sign_url
     *
     * @param signUrl the value for verify_user.sign_url
     *
     * @mbg.generated
     */
    public void setSignUrl(String signUrl) {
        this.signUrl = signUrl == null ? null : signUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verify_user.create_time
     *
     * @return the value of verify_user.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verify_user.create_time
     *
     * @param createTime the value for verify_user.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verify_user.update_time
     *
     * @return the value of verify_user.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verify_user.update_time
     *
     * @param updateTime the value for verify_user.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify_user
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", identityId=").append(identityId);
        sb.append(", sex=").append(sex);
        sb.append(", nationality=").append(nationality);
        sb.append(", birth=").append(birth);
        sb.append(", startDate=").append(startDate);
        sb.append(", endDate=").append(endDate);
        sb.append(", issue=").append(issue);
        sb.append(", address=").append(address);
        sb.append(", faceUrl=").append(faceUrl);
        sb.append(", backUrl=").append(backUrl);
        sb.append(", signUrl=").append(signUrl);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}