package com.covidmanage.mapper;

import com.covidmanage.pojo.AusSpecific;
import com.covidmanage.pojo.AusSpecificExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface AusSpecificMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aus_specific
     *
     * @mbg.generated
     */
    long countByExample(AusSpecificExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aus_specific
     *
     * @mbg.generated
     */
    int deleteByExample(AusSpecificExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aus_specific
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aus_specific
     *
     * @mbg.generated
     */
    int insert(AusSpecific record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aus_specific
     *
     * @mbg.generated
     */
    int insertSelective(AusSpecific record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aus_specific
     *
     * @mbg.generated
     */
    List<AusSpecific> selectByExample(AusSpecificExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aus_specific
     *
     * @mbg.generated
     */
    AusSpecific selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aus_specific
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AusSpecific record, @Param("example") AusSpecificExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aus_specific
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AusSpecific record, @Param("example") AusSpecificExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aus_specific
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AusSpecific record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aus_specific
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AusSpecific record);
}