package com.covidmanage.mapper;

import com.covidmanage.pojo.CityInfo;
import com.covidmanage.pojo.CityInfoExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface CityInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_info
     *
     * @mbg.generated
     */
    long countByExample(CityInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_info
     *
     * @mbg.generated
     */
    int deleteByExample(CityInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_info
     *
     * @mbg.generated
     */
    int insert(CityInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_info
     *
     * @mbg.generated
     */
    int insertSelective(CityInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_info
     *
     * @mbg.generated
     */
    List<CityInfo> selectByExample(CityInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_info
     *
     * @mbg.generated
     */
    CityInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CityInfo record, @Param("example") CityInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CityInfo record, @Param("example") CityInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CityInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CityInfo record);
}