package com.covidmanage.mapper;

import com.covidmanage.pojo.CommunityUser;
import com.covidmanage.pojo.CommunityUserExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface CommunityUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_user
     *
     * @mbg.generated
     */
    long countByExample(CommunityUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_user
     *
     * @mbg.generated
     */
    int deleteByExample(CommunityUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_user
     *
     * @mbg.generated
     */
    int insert(CommunityUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_user
     *
     * @mbg.generated
     */
    int insertSelective(CommunityUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_user
     *
     * @mbg.generated
     */
    List<CommunityUser> selectByExample(CommunityUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_user
     *
     * @mbg.generated
     */
    CommunityUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CommunityUser record, @Param("example") CommunityUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CommunityUser record, @Param("example") CommunityUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CommunityUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CommunityUser record);
}