package com.covidmanage.mapper;

import com.covidmanage.pojo.CommunityManager;
import com.covidmanage.pojo.CommunityManagerExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface CommunityManagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_manager
     *
     * @mbg.generated
     */
    long countByExample(CommunityManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_manager
     *
     * @mbg.generated
     */
    int deleteByExample(CommunityManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_manager
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_manager
     *
     * @mbg.generated
     */
    int insert(CommunityManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_manager
     *
     * @mbg.generated
     */
    int insertSelective(CommunityManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_manager
     *
     * @mbg.generated
     */
    List<CommunityManager> selectByExample(CommunityManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_manager
     *
     * @mbg.generated
     */
    CommunityManager selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_manager
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CommunityManager record, @Param("example") CommunityManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_manager
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CommunityManager record, @Param("example") CommunityManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_manager
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CommunityManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_manager
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CommunityManager record);
}