package com.covidmanage.mapper;

import com.covidmanage.pojo.ReservationSpecific;
import com.covidmanage.pojo.ReservationSpecificExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ReservationSpecificMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservation_specific
     *
     * @mbg.generated
     */
    long countByExample(ReservationSpecificExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservation_specific
     *
     * @mbg.generated
     */
    int deleteByExample(ReservationSpecificExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservation_specific
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservation_specific
     *
     * @mbg.generated
     */
    int insert(ReservationSpecific record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservation_specific
     *
     * @mbg.generated
     */
    int insertSelective(ReservationSpecific record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservation_specific
     *
     * @mbg.generated
     */
    List<ReservationSpecific> selectByExample(ReservationSpecificExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservation_specific
     *
     * @mbg.generated
     */
    ReservationSpecific selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservation_specific
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ReservationSpecific record, @Param("example") ReservationSpecificExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservation_specific
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ReservationSpecific record, @Param("example") ReservationSpecificExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservation_specific
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ReservationSpecific record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservation_specific
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ReservationSpecific record);
}