package com.covidmanage.mapper;

import com.covidmanage.pojo.SupplyInfo;
import com.covidmanage.pojo.SupplyInfoExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface SupplyInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supply_info
     *
     * @mbg.generated
     */
    long countByExample(SupplyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supply_info
     *
     * @mbg.generated
     */
    int deleteByExample(SupplyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supply_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supply_info
     *
     * @mbg.generated
     */
    int insert(SupplyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supply_info
     *
     * @mbg.generated
     */
    int insertSelective(SupplyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supply_info
     *
     * @mbg.generated
     */
    List<SupplyInfo> selectByExample(SupplyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supply_info
     *
     * @mbg.generated
     */
    SupplyInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supply_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SupplyInfo record, @Param("example") SupplyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supply_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SupplyInfo record, @Param("example") SupplyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supply_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SupplyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supply_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SupplyInfo record);
}