package com.covidmanage.mapper;

import com.covidmanage.pojo.SupplyNeed;
import com.covidmanage.pojo.SupplyNeedExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface SupplyNeedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supply_need
     *
     * @mbg.generated
     */
    long countByExample(SupplyNeedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supply_need
     *
     * @mbg.generated
     */
    int deleteByExample(SupplyNeedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supply_need
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supply_need
     *
     * @mbg.generated
     */
    int insert(SupplyNeed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supply_need
     *
     * @mbg.generated
     */
    int insertSelective(SupplyNeed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supply_need
     *
     * @mbg.generated
     */
    List<SupplyNeed> selectByExample(SupplyNeedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supply_need
     *
     * @mbg.generated
     */
    SupplyNeed selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supply_need
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SupplyNeed record, @Param("example") SupplyNeedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supply_need
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SupplyNeed record, @Param("example") SupplyNeedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supply_need
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SupplyNeed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supply_need
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SupplyNeed record);
}