package com.covidmanage.mapper;

import com.covidmanage.pojo.TodoList;
import com.covidmanage.pojo.TodoListExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface TodoListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo_list
     *
     * @mbg.generated
     */
    long countByExample(TodoListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo_list
     *
     * @mbg.generated
     */
    int deleteByExample(TodoListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo_list
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo_list
     *
     * @mbg.generated
     */
    int insert(TodoList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo_list
     *
     * @mbg.generated
     */
    int insertSelective(TodoList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo_list
     *
     * @mbg.generated
     */
    List<TodoList> selectByExample(TodoListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo_list
     *
     * @mbg.generated
     */
    TodoList selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo_list
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TodoList record, @Param("example") TodoListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo_list
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TodoList record, @Param("example") TodoListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo_list
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TodoList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo_list
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TodoList record);
}