package com.covidmanage.mapper;

import com.covidmanage.pojo.TravelInfo;
import com.covidmanage.pojo.TravelInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TravelInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_info
     *
     * @mbg.generated
     */
    long countByExample(TravelInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_info
     *
     * @mbg.generated
     */
    int deleteByExample(TravelInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_info
     *
     * @mbg.generated
     */
    int insert(TravelInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_info
     *
     * @mbg.generated
     */
    int insertSelective(TravelInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_info
     *
     * @mbg.generated
     */
    List<TravelInfo> selectByExampleWithBLOBs(TravelInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_info
     *
     * @mbg.generated
     */
    List<TravelInfo> selectByExample(TravelInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_info
     *
     * @mbg.generated
     */
    TravelInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TravelInfo record, @Param("example") TravelInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_info
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") TravelInfo record, @Param("example") TravelInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TravelInfo record, @Param("example") TravelInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TravelInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(TravelInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TravelInfo record);
}