package com.covidmanage.mapper;

import com.covidmanage.pojo.VaccineLocation;
import com.covidmanage.pojo.VaccineLocationExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface VaccineLocationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vaccine_location
     *
     * @mbg.generated
     */
    long countByExample(VaccineLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vaccine_location
     *
     * @mbg.generated
     */
    int deleteByExample(VaccineLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vaccine_location
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vaccine_location
     *
     * @mbg.generated
     */
    int insert(VaccineLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vaccine_location
     *
     * @mbg.generated
     */
    int insertSelective(VaccineLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vaccine_location
     *
     * @mbg.generated
     */
    List<VaccineLocation> selectByExample(VaccineLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vaccine_location
     *
     * @mbg.generated
     */
    VaccineLocation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vaccine_location
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") VaccineLocation record, @Param("example") VaccineLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vaccine_location
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") VaccineLocation record, @Param("example") VaccineLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vaccine_location
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(VaccineLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vaccine_location
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(VaccineLocation record);
}