package com.covidmanage.mapper;

import com.covidmanage.pojo.VerifyUser;
import com.covidmanage.pojo.VerifyUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VerifyUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify_user
     *
     * @mbg.generated
     */
    long countByExample(VerifyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify_user
     *
     * @mbg.generated
     */
    int deleteByExample(VerifyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify_user
     *
     * @mbg.generated
     */
    int insert(VerifyUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify_user
     *
     * @mbg.generated
     */
    int insertSelective(VerifyUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify_user
     *
     * @mbg.generated
     */
    List<VerifyUser> selectByExample(VerifyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify_user
     *
     * @mbg.generated
     */
    VerifyUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") VerifyUser record, @Param("example") VerifyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") VerifyUser record, @Param("example") VerifyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(VerifyUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(VerifyUser record);
}